import type { FileBundleItem } from "../contracts/index.js";

function jsonFile(obj: unknown): string {
  return JSON.stringify(obj, null, 2) + "\n";
}

export function degradedBackendScaffold(): FileBundleItem[] {
  return [
    {
      path: "backend/package.json",
      content: jsonFile({
        name: "specforge-backend-degraded",
        private: true,
        type: "module",
        scripts: {
          dev: "node src/index.js",
          start: "node src/index.js",
        },
        dependencies: {
          express: "^5.2.1",
          cors: "^2.8.6",
        },
      }),
    },
    {
      path: "backend/src/index.js",
      content: [
        'import express from "express";',
        'import cors from "cors";',
        "",
        "const app = express();",
        "app.use(cors());",
        "app.use(express.json());",
        "",
        'app.get("/health", (_req, res) => {',
        '  res.json({ ok: true, mode: "degraded" });',
        "});",
        "",
        'app.get("/api/notes", (_req, res) => {',
        "  res.json({ notes: [] });",
        "});",
        "",
        'app.post("/api/notes", (req, res) => {',
        "  const title = typeof req.body?.title === \"string\" ? req.body.title : \"Untitled\";",
        "  const content = typeof req.body?.content === \"string\" ? req.body.content : \"\";",
        "  res.status(201).json({ id: \"demo\", title, content });",
        "});",
        "",
        "const port = process.env.PORT ? Number(process.env.PORT) : 3001;",
        "app.listen(port, () => {",
        "  // eslint-disable-next-line no-console",
        "  console.log(`Degraded backend listening on :${port}`);",
        "});",
        "",
      ].join("\n"),
    },
    {
      path: "backend/README.md",
      content: [
        "# Degraded backend scaffold",
        "",
        "This was generated as a fallback because SpecForge timed out.",
        "",
        "## Run",
        "- `npm install`",
        "- `npm run dev`",
        "",
        "## Endpoints",
        "- `GET /health`",
        "- `GET /api/notes`",
        "- `POST /api/notes` body: `{ \"title\": string, \"content\": string }`",
        "",
      ].join("\n"),
    },
  ];
}

export function degradedFrontendScaffold(): FileBundleItem[] {
  return [
    {
      path: "frontend/index.html",
      content: [
        "<!doctype html>",
        "<html>",
        "  <head>",
        '    <meta charset="utf-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
        "    <title>Degraded Notes UI</title>",
        "    <style>",
        "      body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto; margin: 24px; }",
        "      .row { display: flex; gap: 8px; }",
        "      input, textarea { width: 100%; padding: 8px; }",
        "      button { padding: 8px 12px; }",
        "      pre { background: #0b1220; color: #d7e0ff; padding: 12px; border-radius: 8px; overflow: auto; }",
        "      .card { border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; margin-top: 12px; }",
        "    </style>",
        "  </head>",
        "  <body>",
        "    <h1>Notes (degraded scaffold)</h1>",
        '    <p>Point this UI at your backend by setting <code>API_BASE</code> below.</p>',
        "",
        '    <div class="card">',
        '      <label>API_BASE</label>',
        '      <input id="apiBase" value="http://localhost:3001" />',
        "      <div style=\"height: 8px\"></div>",
        '      <div class="row">',
        '        <button id="btnHealth">/health</button>',
        '        <button id="btnList">GET /api/notes</button>',
        "      </div>",
        "    </div>",
        "",
        '    <div class="card">',
        "      <h2>Create note</h2>",
        '      <input id="title" placeholder="Title" />',
        "      <div style=\"height: 8px\"></div>",
        '      <textarea id="content" rows="4" placeholder="Content"></textarea>',
        "      <div style=\"height: 8px\"></div>",
        '      <button id="btnCreate">POST /api/notes</button>',
        "    </div>",
        "",
        '    <h2>Response</h2>',
        '    <pre id="out">{}</pre>',
        "",
        "    <script>",
        "      const out = document.getElementById('out');",
        "      const apiBase = document.getElementById('apiBase');",
        "      const title = document.getElementById('title');",
        "      const content = document.getElementById('content');",
        "",
        "      async function call(path, init) {",
        "        const base = apiBase.value.replace(/\\/$/, '');",
        "        const res = await fetch(base + path, init);",
        "        const text = await res.text();",
        "        try {",
        "          out.textContent = JSON.stringify(JSON.parse(text), null, 2);",
        "        } catch {",
        "          out.textContent = text;",
        "        }",
        "      }",
        "",
        "      document.getElementById('btnHealth').onclick = () => call('/health');",
        "      document.getElementById('btnList').onclick = () => call('/api/notes');",
        "      document.getElementById('btnCreate').onclick = () => call('/api/notes', {",
        "        method: 'POST',",
        "        headers: { 'content-type': 'application/json' },",
        "        body: JSON.stringify({ title: title.value, content: content.value }),",
        "      });",
        "    </script>",
        "  </body>",
        "</html>",
        "",
      ].join("\n"),
    },
    {
      path: "frontend/README.md",
      content: [
        "# Degraded frontend scaffold",
        "",
        "This is a tiny static HTML UI generated as a fallback because SpecForge timed out.",
        "",
        "## Run",
        "- open `frontend/index.html` in a browser",
        "- set `API_BASE` to your backend URL (default `http://localhost:3001`)",
        "",
      ].join("\n"),
    },
  ];
}

